name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      release_as:
        description: 'Release as specific version (optional, e.g., 1.2.3)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Create release PR with release-please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: near-kotlin-rpc
          command: release-pr
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          release-as: ${{ github.event.inputs.release_as }}
          version-file: .release-please-manifest.json
          
      - name: Add comment to PR
        run: |
          echo "Manual release triggered:"
          echo "- Type: ${{ github.event.inputs.release_type }}"
          if [ -n "${{ github.event.inputs.release_as }}" ]; then
            echo "- Version: ${{ github.event.inputs.release_as }}"
          fi